---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci
  namespace: demo
  labels:
    app: fibonacci
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: fibonacci
