---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci1
  namespace: demo
spec:
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
      containers:
      - image: mbilel/fibonacci:latest
        name: fibonacci1
        ports:
        - name: http
          containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi
